version: '3.7'

services:
  naming-server:
    image: breader/naming-server:0.0.1
    mem_limit: 700m
    ports:
    - "8761:8761"
    networks:
      - currency-network
  api-gateway:
    image: breader/api-gateway:0.0.1
    mem_limit: 700m
    ports:
    - "8765:8765"
    networks:
      - currency-network
    depends_on:
      - naming-server
  currency-exchange:
    image: breader/currency-exchange:0.0.1
    mem_limit: 700m
    ports:
    - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - api-gateway
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
  currency-conversion:
    image: breader/currency-conversion:0.0.1
    mem_limit: 700m
    ports:
    - "8100:8100"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - api-gateway
      - currency-exchange
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka

networks:
  currency-network:

